### ISSUE TITLE
Does not appear to work with MacOS trackpad

### ISSUE THREAD

**Issue by npearson72** [warnellw/Zoom-Block#1]
It works for me in Chrome when using the +/- buttons (which is actually not desired) but it does not stop pinch to zoom in MacOS when using Chrome (which is very much desired).

Am I doing something wrong?

**Comment by warnellw** [comment]
Hi - I think pinch to zoom is a MacOS specific (operating system) feature that allows for magnifying any part of the screen (in any app, or even on the desktop). As long as 'ctrl +  (+ / -)' zooming is disabled on a page, Zoom Block has done its job and disabled all forms of _browser_ zooming.

You can probably turn off pinch to zoom in the Touchpad settings in MacOS.
