### ISSUE TITLE
Default to 110 zoom instead of 100?

### ISSUE THREAD

**Issue by robcazzaro** [warnellw/Zoom-Block#2]
Due to my screen size and resolution, all my websites are zoomed to 110. Sometimes my CTRL and trackpad scroll get confused, and I end up zooming in and out when I don't want to. Super annoying

I would love to be able to use your extension, but by default it always reverts everything back to 100. Is there a way to set the default to 110, instead?

**Comment by warnellw** [comment]
Hi there,

Yes - Zoom Block prevents changes to Chrome's default zoom level which can be set/changed in Chrome's settings. Pasting this from the FAQ for convenience:

**Q: Can Zoom Block "lock" a custom zoom level?**
A: The browser extension API does not offer an elegant way to accomplish this. The best option is to change the browser's default zoom level. Chrome's default zoom settings can be found in Settings -> Appearance -> Page Zoom. Zoom Block will then prevent modifications to the set level.

Let me know if this solves your issue!

**Comment by robcazzaro** [comment]
I completely missed that FAQ, and I feel horribly stupid :(

Thanks for pointing that out, it should do exactly what I'm looking for. Closing the issue
