### ISSUE TITLE
Update to modern Chrome

### ISSUE THREAD

**Issue by dharmOS** [warnellw/Zoom-Block#5]
Chrome Store now reports this extension as "This extension may soon no longer be supported because it doesn't follow best practices for Chrome extensions."

Is there any chance of the author updating it, or a fork to enable update to work with Chrome or Edge(based on Chromium) going forward? It would be a shame as it really help manage Accessibility for users where pinch-to-zoom is an encumbrance rather than a feature.

**Comment by warnellw** [comment]
Hey there! Thanks for bringing this to my attention and for your continued interest in Zoom Block! I'm happy to let you know that I just published v2.0.0, which includes a migration to Manifest V3 to ensure continued support and compatibility with Chrome and Chromium-based browsers. 🙂
